/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodDSPConnection */

#ifndef _Included_de_silveryard_basesystem_sound_FmodDSPConnection
#define _Included_de_silveryard_basesystem_sound_FmodDSPConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    getInput
 * Signature: (Lde/silveryard/basesystem/sound/FmodDSP;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_getInput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    getOuput
 * Signature: (Lde/silveryard/basesystem/sound/FmodDSP;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_getOuput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    setMix
 * Signature: (F)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_setMix
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    getMix
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_getMix
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSPConnection
 * Method:    getType
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSPConnection_getType
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
