/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodSystem */

#ifndef _Included_de_silveryard_basesystem_sound_FmodSystem
#define _Included_de_silveryard_basesystem_sound_FmodSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    createSystem
 * Signature: ()Lde/silveryard/basesystem/sound/FmodSystem;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_createSystem
  (JNIEnv *, jclass);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    init
 * Signature: (II)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    update
 * Signature: ()Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_update
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    dispose
 * Signature: ()Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    setOutput
 * Signature: (Lde/silveryard/basesystem/sound/FmodOutputType;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_setOutput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getOutput
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getOutput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getNumDrivers
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getNumDrivers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getDriverInfo
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getDriverInfo
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    setDriver
 * Signature: (I)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_setDriver
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getDriver
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getDriver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    createSound
 * Signature: (Ljava/lang/String;ILde/silveryard/basesystem/sound/FmodCreateSoundExInfo;Lde/silveryard/basesystem/sound/FmodSound;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_createSound
  (JNIEnv *, jobject, jstring, jint, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    createStream
 * Signature: (Ljava/lang/String;ILde/silveryard/basesystem/sound/FmodCreateSoundExInfo;Lde/silveryard/basesystem/sound/FmodSound;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_createStream
  (JNIEnv *, jobject, jstring, jint, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    createDSPByType
 * Signature: (Lde/silveryard/basesystem/sound/FmodDSPType;Lde/silveryard/basesystem/sound/FmodDSP;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_createDSPByType
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    createChannelGroup
 * Signature: (Ljava/lang/String;Lde/silveryard/basesystem/sound/FmodChannelGroup;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_createChannelGroup
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    playSound
 * Signature: (Lde/silveryard/basesystem/sound/FmodSound;ZLde/silveryard/basesystem/sound/FmodChannel;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_playSound
  (JNIEnv *, jobject, jobject, jboolean, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getMasterChannelGroup
 * Signature: (Lde/silveryard/basesystem/sound/FmodChannelGroup;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getMasterChannelGroup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getRecordNumDrivers
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getRecordNumDrivers
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getRectordDriverInfo
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getRectordDriverInfo
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    getRecordPosition
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_getRecordPosition
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    recordStart
 * Signature: (ILde/silveryard/basesystem/sound/FmodSound;Z)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_recordStart
  (JNIEnv *, jobject, jint, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    recordStop
 * Signature: (I)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_recordStop
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSystem
 * Method:    isRecording
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSystem_isRecording
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
