/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodDSP */

#ifndef _Included_de_silveryard_basesystem_sound_FmodDSP
#define _Included_de_silveryard_basesystem_sound_FmodDSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    release
 * Signature: ()Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_release
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setActive
 * Signature: (Z)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getActive
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getActive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setBypass
 * Signature: (Z)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setBypass
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getBypass
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getBypass
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setParameterFloat
 * Signature: (IF)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setParameterFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setParameterInt
 * Signature: (II)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setParameterInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setParameterBool
 * Signature: (IZ)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setParameterBool
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getParameterFloat
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getParameterFloat
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getParameterInt
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getParameterInt
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getParameterBool
 * Signature: (ILde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getParameterBool
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getNumParameters
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getNumParameters
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getInfo
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getInfo
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getType
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getIdle
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getIdle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    setMeteringEnabled
 * Signature: (ZZ)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_setMeteringEnabled
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getMeteringEnabled
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getMeteringEnabled
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodDSP
 * Method:    getMeteringInfo
 * Signature: (Lde/silveryard/basesystem/sound/FmodDSPMeteringInfo;Lde/silveryard/basesystem/sound/FmodDSPMeteringInfo;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodDSP_getMeteringInfo
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
