/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_gui_DisplayManager */

#ifndef _Included_de_silveryard_basesystem_gui_DisplayManager
#define _Included_de_silveryard_basesystem_gui_DisplayManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_initNative
  (JNIEnv *, jclass);

/*
* Class:     de_silveryard_basesystem_gui_DisplayManager
* Method:    nativeGetProcessHandle
* Signature: (JLde/silveryard/basesystem/gui/DisplayHandle;)I
*/
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeGetProcessHandle
(JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeRegisterHandle
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeRegisterHandle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeUnregisterHandle
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeUnregisterHandle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeSetWindowPosition
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;II)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeSetWindowPosition
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeGetWindowPosition
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;Lde/silveryard/basesystem/util/Wrapper;Lde/silveryard/basesystem/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeGetWindowPosition
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeSetWindowAlpha
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;B)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeSetWindowAlpha
  (JNIEnv *, jobject, jobject, jbyte);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeGetWindowAlpha
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;Lde/silveryard/basesystem/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeGetWindowAlpha
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeSetWindowActive
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;Z)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeSetWindowActive
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeGetWindowActive
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;Lde/silveryard/basesystem/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeGetWindowActive
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeSetWindowLayer
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;B)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeSetWindowLayer
  (JNIEnv *, jobject, jobject, jbyte);

/*
 * Class:     de_silveryard_basesystem_gui_DisplayManager
 * Method:    nativeGetWindowLayer
 * Signature: (Lde/silveryard/basesystem/gui/DisplayHandle;Lde/silveryard/basesystem/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_DisplayManager_nativeGetWindowLayer
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
