//
// Created by Beppo on 02/02/17.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_awesome_smarthome_td_gui_SDLLabel */

#ifndef _Included_de_awesome_smarthome_td_gui_SDLLabel
#define _Included_de_awesome_smarthome_td_gui_SDLLabel
#ifdef __cplusplus
extern "C" {
#endif

 /*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelCreate
 * Signature: (ILjava/lang/String;BBBBI)I
 */
	JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelCreate
	(JNIEnv *, jclass, jint, jstring, jbyte, jbyte, jbyte, jbyte, jint);

/*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelDestroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelDestroy
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelSetText
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelSetText
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelSetFont
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelSetFont
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelSetColor
 * Signature: (ICCCC)I
 */
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelSetColor
        (JNIEnv *, jclass, jint, jchar, jchar, jchar, jchar);

/*
* Class:     de_awesome_smarthome_td_gui_SDLLabel
* Method:    labelSetWidth
* Signature: (II)I
*/
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelSetWidth
(JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelGetWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelGetWidth
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_awesome_smarthome_td_gui_SDLLabel
 * Method:    labelGetHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelGetHeight
        (JNIEnv *, jclass, jint);

/*
* Class:     de_awesome_smarthome_td_gui_SDLLabel
* Method:    labelSetAlpha
* Signature: (IB)I
*/
JNIEXPORT jint JNICALL Java_de_awesome_smarthome_td_gui_SDLLabel_labelSetAlpha
(JNIEnv *, jclass, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
