/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_gui_SDLFont */

#ifndef _Included_de_silveryard_basesystem_gui_SDLFont
#define _Included_de_silveryard_basesystem_gui_SDLFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_gui_SDLFont
 * Method:    fontLoad
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_SDLFont_fontLoad
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_silveryard_basesystem_gui_SDLFont
 * Method:    fontUnload
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_gui_SDLFont_fontUnload
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
