/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_logging_LogManager */

#include <string>
#include <bs/bs_def.h>
#include <bs/system/logger.h>

#ifndef _Included_de_silveryard_basesystem_logging_LogManager
#define _Included_de_silveryard_basesystem_logging_LogManager

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_logging_LogManager
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_logging_LogManager_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}

namespace bs {
    namespace system {
        namespace internal{
            BSEXPORT void log_str(const std::string& logger, const std::string& msg, log_message_type type);
        }
    }
}

#endif
#endif
