/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_libdisplaysysjava_DisplaySys */

#ifndef _Included_de_silveryard_basesystem_libdisplaysysjava_DisplaySys
#define _Included_de_silveryard_basesystem_libdisplaysysjava_DisplaySys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    initNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_initNative
  (JNIEnv *, jclass);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    showWindowNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_showWindowNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    hideWindowNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_hideWindowNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    getWindowLayerNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;Lde/silveryard/basesystem/libdisplayjava/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_getWindowLayerNative
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    setWindowLayerNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;I)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_setWindowLayerNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    getWindowPositionNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;Lde/silveryard/basesystem/libdisplayjava/Wrapper;Lde/silveryard/basesystem/libdisplayjava/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_getWindowPositionNative
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    setWindowPositionNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;II)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_setWindowPositionNative
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    getWindowOpacityNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;Lde/silveryard/basesystem/libdisplayjava/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_getWindowOpacityNative
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_libdisplaysysjava_DisplaySys
 * Method:    setWindowOpacityNative
 * Signature: (Lde/silveryard/basesystem/libdisplayjava/Handle;I)I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_libdisplaysysjava_DisplaySys_setWindowOpacityNative
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
