/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodChannel */

#ifndef _Included_de_silveryard_basesystem_sound_FmodChannel
#define _Included_de_silveryard_basesystem_sound_FmodChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    stop
 * Signature: ()Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_stop
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setPaused
 * Signature: (Z)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setPaused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getPaused
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getPaused
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setVolume
 * Signature: (F)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setVolume
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getVolume
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getVolume
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setVolumeRamp
 * Signature: (Z)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setVolumeRamp
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getVolumeRamp
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getVolumeRamp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getAudibility
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getAudibility
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setPitch
 * Signature: (F)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setPitch
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getPitch
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getPitch
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setMute
 * Signature: (Z)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setMute
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getMute
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getMute
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    isPlaying
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_isPlaying
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setFrequency
 * Signature: (F)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setFrequency
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getFrequency
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getFrequency
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setPriority
 * Signature: (I)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setPriority
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getPriority
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getPriority
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setPosition
 * Signature: (II)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getPosition
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;I)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getPosition
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    setChannelGroup
 * Signature: (Lde/silveryard/basesystem/sound/FmodChannelGroup;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_setChannelGroup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannel
 * Method:    getChannelGroup
 * Signature: (Lde/silveryard/basesystem/sound/FmodChannelGroup;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannel_getChannelGroup
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
