/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodSound */

#ifndef _Included_de_silveryard_basesystem_sound_FmodSound
#define _Included_de_silveryard_basesystem_sound_FmodSound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodSound
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodSound_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSound
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodSound_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSound
 * Method:    getLength
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;I)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSound_getLength
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodSound
 * Method:    release
 * Signature: ()Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodSound_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
