/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodChannelGroup */

#ifndef _Included_de_silveryard_basesystem_sound_FmodChannelGroup
#define _Included_de_silveryard_basesystem_sound_FmodChannelGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
