/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodChannelGroup */

#ifndef _Included_de_silveryard_basesystem_sound_FmodChannelGroup
#define _Included_de_silveryard_basesystem_sound_FmodChannelGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    setHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_setHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    addGroup
 * Signature: (Lde/silveryard/basesystem/sound/FmodChannelGroup;ZLde/silveryard/basesystem/sound/FmodDSPConnection;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_addGroup
  (JNIEnv *, jobject, jobject, jboolean, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getNumGroups
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getNumGroups
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getGroup
 * Signature: (ILde/silveryard/basesystem/sound/FmodChannelGroup;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getGroup
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getParentGroup
 * Signature: (Lde/silveryard/basesystem/sound/FmodChannelGroup;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getParentGroup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getName
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getName
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getNumChannels
 * Signature: (Lde/silveryard/basesystem/util/Wrapper;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getNumChannels
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodChannelGroup
 * Method:    getChannel
 * Signature: (ILde/silveryard/basesystem/sound/FmodChannel;)Lde/silveryard/basesystem/sound/FmodResult;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodChannelGroup_getChannel
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
