/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_silveryard_basesystem_sound_FmodCreateSoundExInfo */

#ifndef _Included_de_silveryard_basesystem_sound_FmodCreateSoundExInfo
#define _Included_de_silveryard_basesystem_sound_FmodCreateSoundExInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getHandle
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getLength
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getFileOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getFileOffset
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setFileOffset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setFileOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getNumChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getNumChannels
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setNumChannels
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setNumChannels
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getDefaultFrequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getDefaultFrequency
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setDefaultFrequency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setDefaultFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getFormat
 * Signature: ()Lde/silveryard/basesystem/sound/FmodSoundFormat;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setFormat
 * Signature: (Lde/silveryard/basesystem/sound/FmodSoundFormat;)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setFormat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getDecodeBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getDecodeBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setDecodeBufferSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setDecodeBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getInitialSubSound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getInitialSubSound
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setInitialSubSound
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setInitialSubSound
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getNumSubSounds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getNumSubSounds
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setNumSubSounds
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setNumSubSounds
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getInclusionList
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getInclusionList
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setInclusionList
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setInclusionList
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getDlsName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getDlsName
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setDlsName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setDlsName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getEncryptionKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getEncryptionKey
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setEncryptionKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setEncryptionKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getMaxPolyphony
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getMaxPolyphony
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setMaxPolyphony
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setMaxPolyphony
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getSuggestedSoundType
 * Signature: ()Lde/silveryard/basesystem/sound/FmodSoundType;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getSuggestedSoundType
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setSuggestedSoundType
 * Signature: (Lde/silveryard/basesystem/sound/FmodSoundType;)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setSuggestedSoundType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getFileBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getFileBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setFileBufferSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setFileBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getChannelOrder
 * Signature: ()Lde/silveryard/basesystem/sound/FmodChannelOrder;
 */
JNIEXPORT jobject JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getChannelOrder
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setChannelOrder
 * Signature: (Lde/silveryard/basesystem/sound/FmodChannelOrder;)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setChannelOrder
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getChannelMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getChannelMask
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setChannelMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setChannelMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getInitialSeekPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getInitialSeekPosition
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setInitialSeekPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setInitialSeekPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getInitialSeekPosType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getInitialSeekPosType
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setInitialSeekPosType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setInitialSeekPosType
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getIgnoreSetFilesystem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getIgnoreSetFilesystem
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setIgnoreSetFilesystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setIgnoreSetFilesystem
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getAudioQueuePolicy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getAudioQueuePolicy
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setAudioQueuePolicy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setAudioQueuePolicy
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getMinMidiGranularity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getMinMidiGranularity
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setMinMidiGranularity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setMinMidiGranularity
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    getNonBlockThreadId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_getNonBlockThreadId
  (JNIEnv *, jobject);

/*
 * Class:     de_silveryard_basesystem_sound_FmodCreateSoundExInfo
 * Method:    setNonBlockThreadId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_silveryard_basesystem_sound_FmodCreateSoundExInfo_setNonBlockThreadId
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
